### PR TITLE
Improve login screen (see #5) and fix redirect_uri_mismatch bug (see #7)

### PR DESCRIPTION
**Pull request by PaulRaschke**

### CODE REVIEW

**Comment by thathoff** [comment]
Thanks for your pull request. Great! 👍 

Would you remind to remove the `composer.lock` file from the PR because composer will ignored it anyways when installing the plugin via composer, so we don’t need to add that to the git repo. 

I’m not sure if we should keep the `yarn.lock` since the dependencies are only used for parcel. I would think it’s better to also remove the `yarn.lock`.

**Comment by PaulRaschke** [comment]
Would you mind merging my PR and publishing a new version of the plugin if my changes are sufficient? I'm currently working on a project in which I use your plugin (via composer) and would appreciate it if I could use it with my changes :)

**Comment by thathoff** [comment]
Hi Paul, I’ve reviewed your pull request and it seems to break one feature: When the installation mode has been disabled it still was possible to login with OAuth and create a new account. Is it possible to you to re-add this feature?

**Comment by PaulRaschke** [comment]
Hi Markus, thanks for your quick response. I wasn't aware of this, sorry. I think it should be possible to reimplement this behavior, but I would actually vote against it. In my opinion, the Kirby standard workflow shouldn't be altered and the option to disable the installation should be maintained.
However, I actually missed to add the possibility to create the first user via oauth. Therefore I would suggest to implement this but still keep the option to disable the installation as with Vanilla Kirby.
What are your thoughts?

**Comment by thathoff** [comment]
We definitely need to keep that feature on by default, but it would be an option to make it possible to deactivate for sure. We actually use that a lot because we deploy review installations for Kirby sites where install is disabled but no user is present on the installation. But with this plugin it is possible for us to login and create the first user.

So it would be great if you re-add this feature. Thank you! :)

**Comment by PaulRaschke** [comment]
Okay. If I understand it correctly, you require the ability to securely install the first user via OAuth?
If so, I think the best implementation would be to add the ability to create a user via OAuth to the Panel's installation view, and to add the ability to set the `onlyOauth` option independently for both the login and installation view. This wouldn't behave exactly as previously, but would have the same effect as long as the `panel.install` option is set to `true`. As I said, I wouldn't be entirely happy to change the default workflow by removing the option to disable/enable the Panel installation on a remote server, which Kirby has disabled by default.

**Comment by thathoff** [comment]
Thats right, but it should not be linked to `panel.install`. So make things a bit more clear, the two reasons are: 

1) The main use case for this plugin is: We install review/test websites which have no user at all, so would need to have `panel.install` set to `true`. But because we deploy a copy of the live content here this is no option because otherwise someone can create a new user and maybe access private information or mess with the content. I came up with this plugin idea which solves this quite well. All other options are not that nice (eg. creating users on deployment, etc.)

2) It does not make any difference except it makes everything more complicated. After the first user has been created everyone in the accept list is able to login anyways. Only the first user has to be created via the install-tool.

So I would be fine to have an option to disable creating the first user with OAuth when `panel.install` is false. But that cannot be the default option because otherwise this would change the default behaviour of this plugin and would be a breaking change.

I hope that helps you to understand why things are like things are. ;)

**Comment by PaulRaschke** [comment]
Done, as you suggested!

**Comment by thathoff** [comment]
Great, Thank you. I’ll have a look at it in the next days!

**Comment by thathoff** [comment]
Sorry, for the silence. I tried to install this in out test setup but it did not work. I'm trying to debug this in the next days.

**Comment by PaulRaschke** [comment]
When testing locally it works fine for me. Can you describe what exactly isn't working? Maybe I can try to fix it.

**Comment by thathoff** [comment]
Thank you for asking. It does not add a OAuth button to the login screen at all. I tried to debug this but hat no success and then no time to dive deeper. The code seems to be inside media/plugins/index.js but nothing happens even no error message in the logs.

**Comment by PaulRaschke** [comment]
That's strange. What version of Kirby are you using? Could you provide me a similar project setup so I can try to debug it, or at least a list of the plugins used? Maybe the problems are caused by some interferences.

**Comment by thathoff** [comment]
Sorry for the long period of silence. Building the index.js again fixed the problem. Now everything is working properly. 🎉

I’m closing this PR because I've cherry-picked your commits into the PR https://github.com/thathoff/kirby-oauth/pull/13.

Thanks again for your work! :)

**Pull request closed without merging**
